### ISSUE TITLE
contact us page

### ISSUE THREAD

**Issue by Nazrath10R** [NCHlab/RTPEA#52]
same sized bubbles for all

one rtpea email up top
link to github repo 

tags to the right of the picture bubble and remove the horizontal scroll

make the links work like linkendin or emails

gotta reword some of the bubbles like funding, data generator and collaborator

create the layout and I'll rethink what the right tags for the supervisors are

**Comment by NCHlab** [comment]
![image](https://user-images.githubusercontent.com/32630046/62653143-d7c64f00-b954-11e9-8dfd-4543fb5bce03.png)

![image](https://user-images.githubusercontent.com/32630046/62653191-f1679680-b954-11e9-951c-baca2f68d531.png)

Possible: tweak the scroll bar on top and add github logo

To Do: Reword Labels
